<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="indexes\" />
    <Folder Include="scripts\" />
    <Folder Include="seeds\" />
    <Folder Include="views\" />
  </ItemGroup>

</Project>
