CREATE TABLE [dbo].[bautismo] (
    [id]                      INT           IDENTITY (1, 1) NOT NULL,
    [sacramento]              VARCHAR (200) NOT NULL DEFAULT 1,
    [bautizando_id]           INT           NOT NULL,
    [padre_id]                INT           NOT NULL,
    [madre_id]                INT           NOT NULL,
    [tipo_union_padres]       VARCHAR (50)  NOT NULL,
    [fecha_matrimonio_padres] DATE          NOT NULL,
    [abuelo_materno_id]       INT           NOT NULL,
    [abuela_materna_id]       INT           NOT NULL,
    [abuelo_paterno_id]       INT           NOT NULL,
    [abuela_paterna_id]       INT           NOT NULL,
    [padrino_id]              INT           NOT NULL,
    [madrina_id]              INT           NOT NULL,
    [declarante_id]           INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    FOREIGN KEY ([abuela_materna_id]) REFERENCES [dbo].[persona] ([id]),
    FOREIGN KEY ([abuela_paterna_id]) REFERENCES [dbo].[persona] ([id]),
    FOREIGN KEY ([abuelo_materno_id]) REFERENCES [dbo].[persona] ([id]),
    FOREIGN KEY ([abuelo_paterno_id]) REFERENCES [dbo].[persona] ([id]),
    FOREIGN KEY ([bautizando_id]) REFERENCES [dbo].[persona] ([id]),
    FOREIGN KEY ([declarante_id]) REFERENCES [dbo].[persona] ([id]),
    FOREIGN KEY ([madre_id]) REFERENCES [dbo].[persona] ([id]),
    FOREIGN KEY ([madrina_id]) REFERENCES [dbo].[persona] ([id]),
    FOREIGN KEY ([padre_id]) REFERENCES [dbo].[persona] ([id]),
    FOREIGN KEY ([padrino_id]) REFERENCES [dbo].[persona] ([id])
);

